### ISSUE TITLE
undefined method `fqdn' for #<Chef::Node::Attribute:0x0000000002f1b588>>

### ISSUE THREAD

**Issue by lavanyaruth** [zuazo/chef-handler-sns#12]
chef client version iam using is 14.4.56

can anyone please tell me what went wrong in this.

same code is working fine with chef-client version of 12.7 but doesn't work with versions > 12.7

Running handlers:
[2018-09-20T09:41:46+00:00] ERROR: Report handler Chef::Handler::Sns raised #<NoMethodError: undefined method `fqdn' for #<Chef::Node::Attribute:0x0000000002f1b588>>
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/node.rb:263:in `public_send'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/node.rb:263:in `method_missing'
[2018-09-20T09:41:46+00:00] ERROR: (erubis):3:in `block in evaluate'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `instance_eval'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `evaluate'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-handler-sns-2.1.0/lib/chef/handler/sns.rb:302:in `sns_body'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-handler-sns-2.1.0/lib/chef/handler/sns.rb:138:in `report'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/handler.rb:257:in `run_report_unsafe'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/handler.rb:245:in `run_report_safely'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/handler.rb:123:in `block in run_report_handlers'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/handler.rb:121:in `each'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/handler.rb:121:in `run_report_handlers'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/handler.rb:133:in `block in <class:Handler>'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/client.rb:445:in `block in run_completed_successfully'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/client.rb:444:in `each'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/client.rb:444:in `run_completed_successfully'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/client.rb:301:in `run'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/application.rb:279:in `block in run_chef_client'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/local_mode.rb:44:in `with_server_connectivity'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/application.rb:261:in `run_chef_client'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/application/client.rb:440:in `run_application'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/application.rb:66:in `run'
[2018-09-20T09:41:46+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/bin/chef-client:25:in `<top (required)>'
[2018-09-20T09:41:46+00:00] ERROR: /usr/bin/chef-client:75:in `load'
[2018-09-20T09:41:46+00:00] ERROR: /usr/bin/chef-client:75:in `<main>'
  - Chef::Handler::Sns
Running handlers complete

Deprecated features used!
  Resource chef_handler has been loaded from a cookbook. The resource chef_handler is now included in Chef and will take precedence over the existing cookbook resource in the next major release of Chef (15.0, April 2019). You may be able to remove this cookbook dependency from your runlist if you do not use other recipes/resources/libraries from the cookbook. Alternatively there may be a newer version of this cookbook without the chef_handler resource. at 1 location:
    - /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/log.rb:51:in `caller_location'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
